"""initial migration

Revision ID: bd5996cb7073
Revises: 
Create Date: 2025-04-26 12:50:52.814520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd5996cb7073'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Adicionar a coluna 'jti' como nullable inicialmente
    op.add_column('access_token_blacklist', sa.Column('jti', sa.String(length=36), nullable=True))
    op.create_index('idx_blacklist_jti', 'access_token_blacklist', ['jti'], unique=False)
    
    # Preencher a coluna 'jti' com valores válidos (UUID)
    op.execute("""
        UPDATE access_token_blacklist
        SET jti = gen_random_uuid()::text
    """)

    # Alterar a coluna 'jti' para NOT NULL após preenchimento
    op.alter_column('access_token_blacklist', 'jti', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_blacklist_jti', table_name='access_token_blacklist')
    op.drop_column('access_token_blacklist', 'jti')
    # ### end Alembic commands ###
